site_name: Archivist Documentation
site_description: Documentation for Archivist by Integral Business Intelligence
site_url: https://integral-business-intelligence.github.io/archivist/

theme:
  name: readthedocs
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables

nav:
  - Home: index.md
  - Usage:
    - Query Tab: tabs/query.md
    - Pre-Process Tab: tabs/pre-process.md
    - Upload Tab: tabs/pre-process.md
    - Browse Tab: tabs/pre-process.md
    - Inspect Tab: tabs/pre-process.md
    - AI Settings Tab: tabs/pre-process.md
    - Help and Licensing Tab: tabs/pre-process.md
  - Examples: examples.md
