site_name: Archivist Documentation
site_description: Documentation for Archivist by Integral Business Intelligence
site_url: https://integral-business-intelligence.github.io/archivist/

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    primary: grey

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables

nav:
  - Home: 
    - Overview: index.md
    - Licensing: license.md
  - Usage:
    - Query: tabs/query.md
    - Pre-Process: tabs/pre-process.md
    - Upload: tabs/upload.md
    - Browse: tabs/browse.md
    - Inspect: tabs/inspect.md
    - AI Settings: tabs/ai_settings.md
    - Help and Licensing: tabs/help_and_licensing.md
  - Concepts:
    - Retrieval Augmented Generation: concepts/rag.md
    - Use Cases: concepts/usecases.md
    - File Sets: concepts/filesets.md
    - Privacy: concepts/privacy.md
    - Data Portability: concepts/portability.md
  - About:
    - Integral Business Intelligence: about/integralbi.md
    - Capability Demo: about/demo.md