site_name: Archivist Documentation
site_description: Documentation for Archivist by Integral Business Intelligence
site_url: https://integral-business-intelligence.github.io/archivist/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables

nav:
  - Home: index.md
  - Usage:
    - Query Tab: tabs/query.md
    - Pre-Process Tab: tabs/pre-process.md
    - Upload Tab: tabs/upload.md
    - Browse Tab: tabs/browse.md
    - Inspect Tab: tabs/inspect.md
    - AI Settings Tab: tabs/ai_settings.md
    - Help and Licensing Tab: tabs/help_and_licensing.md
